name: flutter_inset_box_shadow
description: "This package extends BoxShadow and BoxDecoration to support the inset property."
version: 0.0.1


environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
